name: Unit Test and Reveal CTF Flag

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      id: tests
      run: |
        pytest > result.log
        if grep -q "FAILURES" result.log; then
          exit 1
        fi

    - name: Provide feedback
      if: success()
      uses: actions/github-script@v5
      with:
        script: |
          const { github, context } = require('@actions/github');
          const pr = context.payload.pull_request;
          const body = `
          ### Congratulations! 🎉
          All your unit tests have passed successfully.
          Great job! Keep up the good work.
          
          Here is your CTF flag: \`${{ secrets.CTF_FLAG }}\`
          `;
          github.rest.issues.createComment({
            ...context.repo,
            issue_number: pr.number,
            body: body,
          });

